const mongose = require('mongoose');
const inventarioShema = new mongose.Schema({
PresentacionInsumo:             {type: String},
ProveedorInsumo:                {type: String},
ExistenciasStock:               {type: Number},
ExistenciasLlenado:             {type: String},
ExistenciasProductoTerminado:   {type: String},
ExistenciasDaniadas:            {type: String},
ExistenciasLote:                {type: String},
ExistenciasRecepcion:           {type: Date},
FechaRevisionExistencia:        {type: Date},
FechaRegistroIngresoExistencia: {type: Date},
NoMuestras:                     {type: String},
OlorExtraño:                    {type: String},
Apariencia:                     {type: String},
ContaminacionInterna:           {type: String},
AcabadoDaniadoEnvaseRoto:       {type: String},
RevadasDiametroExteriorAcabado: {type: String},
ContaminacionAparienciaExterna: {type: String},
BotellasAbulladuras:            {type: String},
MarcasRalladuras:               {type: String},
Desgaste:                       {type: String},
Burbujas:                       {type: String},
Perlesencia:                    {type: String},
PuntoInyeccionDecentrado:       {type: String},
Altura_mm:                      {type: String},
Peso_g:                         {type: String},
ResponsableRevision:            {type: String},
AprobadoRechazado:              {type: String},
ObservacionesRevision:          {type: String},
CostoExistencia:                {type: Number},
Rosca_ok:                       {type: String},
Material_Extranio:              {type: String},
tapa_liner:                     {type: String},
nivel_inspeccion_s4:            {type: String},
tamanio_muestra:                {type: String},
aceptar_inspeccion_s4:          {type: String},
rechazar_inspeccion_s4:         {type: String},
ResponsableRecepcionExistencia:  {type: String}
})
module.exports = mongose.model('inventarios', inventarioShema)